apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-deployment
  annotations:
    commitID: "035c74bc501e06722f23e29e1a10cd3604198a27"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-spring-boot:035c74bc501e06722f23e29e1a10cd3604198a27'
          ports:
            - containerPort: 80
