apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-deployment
  annotations:
    commitID: "4ae52610e7981cd8be5cf3ada0e77c5042ce0371"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-spring-boot:4ae52610e7981cd8be5cf3ada0e77c5042ce0371'
          ports:
            - containerPort: 80
