apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-deployment
  annotations:
    commitID: "54934c6ce7cbc4bc2cff69cb6b2dd6966a9226ec"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-spring-boot:54934c6ce7cbc4bc2cff69cb6b2dd6966a9226ec'
          ports:
            - containerPort: 80
