apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-deployment
  annotations:
    commitID: "64ee59af6bf0b72d3e6d560690e441401a720a53"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-spring-boot:64ee59af6bf0b72d3e6d560690e441401a720a53'
          ports:
            - containerPort: 80
