apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-deployment
  annotations:
    commitID: "ea1388ad9fb9a114380b333d1ce763c2eec1cbfa"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-spring-boot:ea1388ad9fb9a114380b333d1ce763c2eec1cbfa'
          ports:
            - containerPort: 80
