apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-deployment
  annotations:
    commitID: "3b7e5bc7f3785b8ab387326dac640ce04be73de8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-spring-boot:3b7e5bc7f3785b8ab387326dac640ce04be73de8'
          ports:
            - containerPort: 80
