apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-deployment
  annotations:
    commitID: "0b74b079a0b37d6050ba41c7ba206c96e6385d0f"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-spring-boot:0b74b079a0b37d6050ba41c7ba206c96e6385d0f'
          ports:
            - containerPort: 80
