apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-deployment
  annotations:
    commitID: "b3d8599e082963a9ef0a1334b560c1edaaeaa40d"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-spring-boot:b3d8599e082963a9ef0a1334b560c1edaaeaa40d'
          ports:
            - containerPort: 80
