apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-song-quotes-deployment
  annotations:
    commitID: "21b2394cc946084267390a608e73a92ef389fba0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-song-quotes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-song-quotes
    spec:
      containers:
        - name: api-song-quotes
          image: 'xavelo/api-song-quotes:21b2394cc946084267390a608e73a92ef389fba0'
          ports:
            - containerPort: 80
